# Project information
site_name: Project documentation
site_description: "The documentation for Project (RE)SOURCES RELATIONNELLES pertains to the development of a web and mobile application.."
site_author: "Kitaah"

repo_name: "project_documentation"
repo_url: "https://github.com/kitaah/project_documentation"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  font:
    text: Inter
  palette:
    primary: "indigo"
    accent: "indigo"
  features:
    - tabs
    - search.suggest
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Page tree
nav:
  - "Home": "index.md"
  - "DDEV":
    - "General": "DDEV/general.md"
    - "Installation": "DDEV/installation.md"
    - "Laravel quickstart": "DDEV/laravel-quickstart.md"
  - "Laravel":
      - "General": "Laravel/general.md"
  - "PHP":
      - "PHP 8.3": "PHP/php8.3.md"
      - "PHP Documentor": "PHP/phpdocumentor.md"